root: /
permalink: /:title
markdown: rdiscount
lsi: false
rdiscount:
    extensions: [smart]

cdn: http://cdn.ekynoxe.com
hostname: ekynoxe.com
title: Mathieu Davy's triathlon ramblings

# Pagination (news)
paginate: 7
paginate_path: "page:num"

# Comments configuration
paginate_categories: 4
category_path: "categories/:cat"
category_page_path: "page:num"

# RSS plugin
name: Ekynoxe - Mathieu Davy's triathlon ramblings
url: http://tri.ekynoxe.com
author: hello@ekynoxe.com (Mathieu Davy)
description: Mathieu Davy's triathlon ramblings

plugins: [jekyll-paginate]
